### ISSUE TITLE
It tries to add a comment to line number 0

### ISSUE THREAD

**Issue by kingoleg** [AmadeusITGroup/sonar-stash#103]
```
build	21-Mar-2017 12:03:35	[INFO] SonarQube issues reported to Stash by user "sonarqube" have been reset
build	21-Mar-2017 12:03:35	[INFO] New SonarQube issues have been reported to Stash.
build	21-Mar-2017 12:03:35	[ERROR] Unable to link SonarQube issues to Stash
build	21-Mar-2017 12:03:35	org.sonar.plugins.stash.exceptions.StashClientException: Unable to post a comment to Test #27. Received 400: null: 0 is not a valid line number. Diff lines start from 1.
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.client.StashClient.validateResponse(StashClient.java:298) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.client.StashClient.performRequest(StashClient.java:288) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.client.StashClient.postCreate(StashClient.java:259) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.client.StashClient.postCommentLineOnPullRequest(StashClient.java:168) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.StashRequestFacade.postCommentPerIssue(StashRequestFacade.java:206) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.StashRequestFacade.postCoverageReport(StashRequestFacade.java:150) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.StashIssueReportingPostJob.postInfoAndPRsActions(StashIssueReportingPostJob.java:151) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.StashIssueReportingPostJob.updateStashWithSonarInfo(StashIssueReportingPostJob.java:115) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.plugins.stash.StashIssueReportingPostJob.executeOn(StashIssueReportingPostJob.java:55) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:87) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	21-Mar-2017 12:03:35		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
```

**Comment by kingoleg** [comment]
I run it with coverage support. And I have a coverage issue. And sonar use file type issue in that case. I think, this is a root of issue

**Comment by t-8ch** [comment]
When did you build this SNAPSHOT? Yesterday a fix for this has been merged/

**Comment by kingoleg** [comment]
Ok, I will rebuild the plugin again

**Comment by kingoleg** [comment]
Fixed in master
