### ISSUE TITLE
Getting error "The path query parameter is required when retrieving comments."

### ISSUE THREAD

**Issue by oscarfh** [AmadeusITGroup/sonar-stash#144]
Hi,
I am trying to configure the plugin, but I get the following error:

```
org.sonar.plugins.stash.exceptions.StashClientException: Unable to post a comment to <repo> #<PR-ID>. Received 400: null: The path query parameter is required when retrieving comments.
	at org.sonar.plugins.stash.client.StashClient.validateResponse(StashClient.java:362)
	at org.sonar.plugins.stash.client.StashClient.performRequest(StashClient.java:350)
	at org.sonar.plugins.stash.client.StashClient.postCreate(StashClient.java:316)
	at org.sonar.plugins.stash.client.StashClient.postCommentOnPullRequest(StashClient.java:105)
	at 
org.sonar.plugins.stash.StashRequestFacade.postAnalysisOverview(StashRequestFacade.java:73)
```
The request done is

```
Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /rest/api/1.0/projects/<Proj>/repos/<repo>/pull-requests/<ID>/comments HTTP/1.1
Accept: application/json
Accept-Encoding: gzip,deflate
Host: <host>
Authorization: Basic XXX
User-Agent: SonarQube/6.4.0.25310 Stash/1.3.0-SNAPSHOT AHC/2.0

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 400 
X-AREQUESTID: @2CN750x989x31283666x0
X-ASEN: SEN-7609194
X-AUSERID: 356
X-AUSERNAME: <username>
Cache-Control: no-cache, no-transform
Vary: X-AUSERNAME,Accept-Encoding
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
Content-Type: application/json;charset=UTF-8
Date: Tue, 22 Aug 2017 16:29:03 GMT
```

This causes me to do not get any comment in my pull request.

Do I need to configure something on Bitbucket to allow this?
Using the url in the browser yields the same result with the same message.
Bitbucket Version: Atlassian Bitbucket v5.1.0

**Comment by t-8ch** [comment]
@oscarfh Note: you leaked your credentials in the HTTP debug log (in the Basic header).
I removed them, but you should regard them as compromised.

**Comment by oscarfh** [comment]
@t-8ch thanks a lot!

**Comment by t-8ch** [comment]
@oscarfh Something is weird. The http debug log show a GET request while the stack trace and the code suggest we should be doing a POST.

**Comment by oscarfh** [comment]
@t-8ch Is there anything I can provide to help the analysis?

**Comment by t-8ch** [comment]
@oscarfh Can you make sure that there are no other debug logs involved?
Also which version of the plugin are you using?

**Comment by t-8ch** [comment]
@oscarfh I assume there is some kind of redirection happening which makes the http client switch its method. Can you check if there is a 301 or 302 redirect coming before?

**Comment by oscarfh** [comment]
@t-8ch I am using the version that is in master. I followed the instructions on the readme file.

```
16:34:52.453 [INFO] [org.sonarqube.gradle.SonarQubeTask] New SonarQube issues have been reported to Stash.
16:34:52.470 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Using new Channel '[id: 0x62512621, L:/xx:48332 - R:HOST/xx:80]' for 'POST' to '/rest/api/1.0/projects/Project/repos/Repo/pull-requests/1099/comments'
16:34:52.476 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] 

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(freed))
POST /rest/api/1.0/projects/Project/repos/REPO/pull-requests/1099/comments HTTP/1.1
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip,deflate
Content-Length: 8574
Host: <HOST>
Authorization: Basic XX
User-Agent: SonarQube/6.4.0.25310 Stash/1.3.0-SNAPSHOT AHC/2.0

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://<HOST>/rest/api/1.0/projects/Project/repos/REPO/pull-requests/1099/comments
Connection: close

16:34:52.476 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Redirecting to https://<HOST>/rest/api/1.0/projects/Project/repos/REPO/pull-requests/1099/comments
16:34:52.477 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Sending redirect to https://<HOST>/rest/api/1.0/projects/Project/repos/REPO/pull-requests/1099/comments
16:34:52.477 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Closing Channel [id: 0x62512621, L:/XX:48332 - R:<HOST>/XX:80] 
16:34:52.477 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Using pooled Channel '[id: 0x5cd97a97, L:/XX:52702 - R:<HOST>/XX:443]' for 'GET' to 'https://<HOST>/rest/api/1.0/projects/Project/repos/REPO/pull-requests/1099/comments'
16:34:52.477 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Using open Channel [id: 0x5cd97a97, L:/XX:52702 - R:<HOST>/XX:443] for GET '/rest/api/1.0/projects/Project/repos/REPO/pull-requests/1099/comments'
16:34:52.477 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Channel Closed: [id: 0x62512621, L:/XX:48332 ! R:<HOST>/XX:80] with attribute INSTANCE
16:34:52.479 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Entry count for : https://<HOST>:443 : 0
16:34:52.479 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Closed 0 connections out of 0 in 0 ms
16:34:52.625 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] 

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /rest/api/1.0/projects/Project/repos/REPO/pull-requests/1099/comments HTTP/1.1
Accept: application/json
Accept-Encoding: gzip,deflate
Host: <HOST>
Authorization: Basic XX
User-Agent: SonarQube/6.4.0.25310 Stash/1.3.0-SNAPSHOT AHC/2.0

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 400 
X-AREQUESTID: @2CN750x994x31284931x0
X-ASEN: SEN-7609194
X-AUSERID: 356
X-AUSERNAME: USER
Cache-Control: no-cache, no-transform
Vary: X-AUSERNAME,Accept-Encoding
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
Content-Type: application/json;charset=UTF-8
Date: Tue, 22 Aug 2017 16:34:51 GMT
```

**Comment by t-8ch** [comment]
Well, wenn the http client receives a 302 redirection it has to switch to GET as per the standard.
So whoever is sending this redirecting is at fault.

**Comment by t-8ch** [comment]
The redirect is not coming from BitBucket, so probably some reverse proxy.
It seems it is to force users to https. Can you change the stash url in your configuration to point to the https version directly?

**Comment by oscarfh** [comment]
@t-8ch I think it is already using the https version. Today is a busy day for the team so reactivating the plugin might cause us problems. I will do in the end of the day and get back to you.

**Comment by t-8ch** [comment]
`Using new Channel '[id: 0x62512621, L:/xx:48332 - R:HOST/xx:80]` mentions port 80 -> http.

Sure.

**Comment by oscarfh** [comment]
Yes, the url was set to http. Changing it fixed.
I am having other issues now, but I will research before opening a new ticket.
Thanks for your help!

**Comment by t-8ch** [comment]
You are welcome!
