### ISSUE TITLE
Several Issues when executing org.sonar.plugins.stash.StashIssueReportingPostJob

### ISSUE THREAD

**Issue by hax0rdlux3** [AmadeusITGroup/sonar-stash#153]
Hello,

 New to this plugin and Sonar in general, any assistance resolving is appreciated:

`INFO: ANALYSIS SUCCESSFUL
INFO: Executing post-job org.sonar.plugins.stash.StashIssueReportingPostJob
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 7.894s
INFO: Final Memory: 49M/326M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException: principal
        at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
        at org.asynchttpclient.Realm.<init>(Realm.java:88)
        at org.asynchttpclient.Realm.<init>(Realm.java:37)
        at org.asynchttpclient.Realm$Builder.build(Realm.java:491)
        at org.sonar.plugins.stash.client.StashClient.performRequest(StashClient
.java:287)
        at org.sonar.plugins.stash.client.StashClient.get(StashClient.java:258)
        at org.sonar.plugins.stash.client.StashClient.getUser(StashClient.java:1
82)
        at org.sonar.plugins.stash.StashRequestFacade.getSonarQubeReviewer(Stash
RequestFacade.java:327)
        at org.sonar.plugins.stash.StashIssueReportingPostJob.updateStashWithSon
arInfo(StashIssueReportingPostJob.java:74)
        at org.sonar.plugins.stash.StashIssueReportingPostJob.executeOn(StashIss
ueReportingPostJob.java:52)
        at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.ja
va:66)
        at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.ja
va:55)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseE
xecutor.java:84)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanCon
tainer.java:179)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:129)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer
.java:261)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectSc
anContainer.java:256)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanC
ontainer.java:245)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:129)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:
84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:144)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:129)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContain
er.java:119)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.exec
ute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(Iso
latedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner
.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScann
er.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR:
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.`

**Comment by t-8ch** [comment]
Hi @hax0rdlux3 ,
it looks like you are *not* using credentials to authenticate to BitBucket, is this correct?
I will take a look at the code and try to fix it.

**Comment by t-8ch** [comment]
This is now fixed on master. Can you give it a spin?

**Comment by hax0rdlux3** [comment]
Hello t-8ch,

 Yes, correct and thanks - greatly appreciated. I'll update from master and try it out.
