### ISSUE TITLE
Failure executing post-job class StashIssueReportingPostJob

### ISSUE THREAD

**Issue by almorelle** [AmadeusITGroup/sonar-stash#6]
I'm unable to report issues to a Stash Pull Request using the Stash plugin for Sonarqube.

I have a very standard and simple project. I'm running the analysis from the maven plugin inside a Jenkins job. I use the following options:

-Dsonar.analysis.mode=incremental -Dstash.notification -Dstash.project=${projectCode} -Dstash.repository=${repositoryName} -Dstash.pullrequest.id=${pullRequestId} -Dsonar.stash.password=${password}

I'm getting errors about some unsatisfied dependency "org.sonar.api.notifications.NotificationManager" which I believe to be included in org.codehaus.sonar:sonar-plugin-api. Would you see any reason why it wouldn't be resolved and if this has anything to do with your plugin?

Let me know if I can provide more information. Thank you in advance for your help.

Maven version 3.3.3
Sonarqube version 5.1.2

**Comment by almorelle** [comment]
[INFO] [13:54:34.755] Export issues to /home/jenkins/workspace/dummy-project-pull-request-builder/target/sonar/sonar-report.json
[INFO] [13:54:34.760] ANALYSIS SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.609 s
[INFO] Finished at: 2015-10-06T13:54:34+00:00
[INFO] Final Memory: 22M/330M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar (default-cli) on project dummy-project: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@6850b758:219<[Immutable]:org.picocontainer.DefaultPicoContainer@5acc9fdf:19<[Immutable]:org.picocontainer.DefaultPicoContainer@4bc59b27:49<| -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar (default-cli) on project dummy-project: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@6850b758:219<[Immutable]:org.picocontainer.DefaultPicoContainer@5acc9fdf:19<[Immutable]:org.picocontainer.DefaultPicoContainer@4bc59b27:49<|
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@6850b758:219<[Immutable]:org.picocontainer.DefaultPicoContainer@5acc9fdf:19<[Immutable]:org.picocontainer.DefaultPicoContainer@4bc59b27:49<|
	at org.codehaus.mojo.sonar.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:41)
	at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:139)
	at org.codehaus.mojo.sonar.SonarMojo.execute(SonarMojo.java:132)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@6850b758:219<[Immutable]:org.picocontainer.DefaultPicoContainer@5acc9fdf:19<[Immutable]:org.picocontainer.DefaultPicoContainer@4bc59b27:49<|
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
	at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:698)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:620)
	at org.picocontainer.containers.ImmutablePicoContainer.getComponent(ImmutablePicoContainer.java:40)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:717)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:631)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:605)
	at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:586)
	at org.sonar.api.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:217)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.completeBatchExtensions(BatchExtensionDictionnary.java:119)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getExtensions(BatchExtensionDictionnary.java:113)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getFilteredExtensions(BatchExtensionDictionnary.java:91)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.select(BatchExtensionDictionnary.java:68)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:49)
	at org.sonar.batch.phases.DatabaseLessPhaseExecutor.execute(DatabaseLessPhaseExecutor.java:103)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:264)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:235)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:230)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:220)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
	at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57)
	at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45)
	at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:135)
	... 23 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
SonarQube analysis completed: FAILURE
Build step 'SonarQube' changed build result to FAILURE
Build step 'SonarQube' marked build as failure
Notified Stash for commit with id 633f86b352c5fc2943e2ebc88f3973477cb5972d
Finished: FAILURE

**Comment by acopet** [comment]
Hello Alexis,
We have difficulties to reproduce this issue with SQ version 5.1.2: could you please send me the full trace from your SQ run and the list of installed plugin? 

We are really interested by your feedback like the plugin, so far, supports SQ until LTS version 4.5.4.

**Comment by almorelle** [comment]
Thank you for your answer. This is from the access.log, nothing showed up in the sonar.log during the analysis.

```
127.0.0.1 - - [09/Oct/2015:16:18:27 +0200] "GET /sonar/api/server/version HTTP/1.1" 200 5 "-" "Java/1.8.0_45"
127.0.0.1 - - [09/Oct/2015:16:18:27 +0200] "GET /sonar/api/server/version HTTP/1.1" 200 5 "-" "Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:27 +0200] "GET /sonar/batch_bootstrap/index HTTP/1.1" 200 68 "-" "Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:35 +0200] "GET /sonar/batch/sonar-batch-maven-compat-5.1.2.jar HTTP/1.1" 200 18587509 "-" "Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:37 +0200] "GET /sonar/batch/global HTTP/1.1" 200 - "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:37 +0200] "GET /sonar/deploy/plugins/index.txt HTTP/1.1" 200 1485 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:37 +0200] "GET /sonar/deploy/plugins/javascript/sonar-javascript-plugin-2.8.jar HTTP/1.1" 200 1580406 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:39 +0200] "GET /sonar/deploy/plugins/findbugs/sonar-findbugs-plugin-3.3.jar HTTP/1.1" 200 7080266 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:39 +0200] "GET /sonar/deploy/plugins/coverity/sonar-coverity-plugin-0.1.jar HTTP/1.1" 200 1261300 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:40 +0200] "GET /sonar/deploy/plugins/stash/sonar-stash-plugin-1.0.0.jar HTTP/1.1" 200 3275429 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:42 +0200] "GET /sonar/deploy/plugins/android/sonar-android-plugin-1.1.jar HTTP/1.1" 200 8582029 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:43 +0200] "GET /sonar/deploy/plugins/l10nfr/sonar-l10n-fr-plugin-1.13.jar HTTP/1.1" 200 37432 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:43 +0200] "GET /sonar/deploy/plugins/l10nen/sonar-l10n-en-plugin-5.1.2.jar HTTP/1.1" 200 4103 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:43 +0200] "GET /sonar/deploy/plugins/issueassign/sonar-issue-assign-plugin-1.6.jar HTTP/1.1" 200 422514 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:43 +0200] "GET /sonar/deploy/plugins/scmmercurial/sonar-scm-mercurial-plugin-1.1.1.jar HTTP/1.1" 200 16802 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:44 +0200] "GET /sonar/deploy/plugins/scmgit/sonar-scm-git-plugin-1.1.jar HTTP/1.1" 200 2680693 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:44 +0200] "GET /sonar/deploy/plugins/ldap/sonar-ldap-plugin-1.4.jar HTTP/1.1" 200 30646 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:45 +0200] "GET /sonar/deploy/plugins/cxx/sonar-cxx-plugin-1.0-SNAPSHOT.jar HTTP/1.1" 200 2030249 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:47 +0200] "GET /sonar/deploy/plugins/checkstyle/sonar-checkstyle-plugin-2.3.jar HTTP/1.1" 200 2404852 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:48 +0200] "GET /sonar/deploy/plugins/pmd/sonar-pmd-plugin-2.4.1.jar HTTP/1.1" 200 4281231 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:49 +0200] "GET /sonar/deploy/plugins/core/sonar-core-plugin-5.1.2.jar HTTP/1.1" 200 143490 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:49 +0200] "GET /sonar/deploy/plugins/java/sonar-java-plugin-3.5.jar HTTP/1.1" 200 2965677 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:51 +0200] "GET /sonar/deploy/plugins/csharp/sonar-csharp-plugin-4.2.jar HTTP/1.1" 200 8721144 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:52 +0200] "GET /sonar/deploy/plugins/cobertura/sonar-cobertura-plugin-1.6.3.jar HTTP/1.1" 200 10325 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:52 +0200] "GET /sonar/deploy/plugins/emailnotifications/sonar-email-notifications-plugin-5.1.2.jar HTTP/1.1" 200 598307 "-" "SonarQube Maven/3.3.3"
127.0.0.1 - - [09/Oct/2015:16:18:53 +0200] "GET /sonar/batch/project?key=com.alcatel_lucent.sf%3Adummy-project&amp;preview=true HTTP/1.1" 200 - "-" "SonarQube Maven/3.3.3"
```

Plugin list and versions:

```
Android [android] 	1.1
Checkstyle [checkstyle] 	2.3
Cobertura [cobertura] 	1.6.3
ALU Coverity [coverity] 	0.1 
C# [csharp] 	4.2
C++ (Community) [cxx] 	1.0-SNAPSHOT
Findbugs [findbugs] 	3.3
Issue Assign [issueassign] 	1.6
Java [java] 	3.5
JavaScript [javascript] 	2.8
French Pack [l10nfr] 	1.13
LDAP [ldap] 	1.4
PMD [pmd] 	2.4.1
Git [scmgit] 	1.1
Mercurial [scmmercurial] 	1.1.1
Stash [stash] 	1.0.0
```

No error while deploying the plugin when SQ starts:
```
2015.10.07 11:55:06 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Install plugins
2015.10.07 11:55:06 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin JavaScript / 2.8 / 53ffb46f827d24be6173dc5a44afd74b2c0b4e3f
2015.10.07 11:55:06 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Findbugs / 3.3 / e1a76544ee6aed765106e7e2bb64072adf63ccaf
2015.10.07 11:55:06 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin ALU Coverity / 0.1
2015.10.07 11:55:06 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Stash / 1.0.0
2015.10.07 11:55:06 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Android / 1.1 / 9ab2bbcc83177e67c74d365f009bfe05bf38c7e3
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin French Pack / 1.13 / 75ee9eb6def89803c48e06a48d6c155b93e8e3f6
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin English Pack / 5.1.2 / 2a52a7106b2bfbd659c591c2d6fc09ad0ab2db5c
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Issue Assign / 1.6 / c24b76cdb882383411f58511cf9d8384f0539584
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Mercurial / 1.1.1 / dcdbfacac9483a76f4f7c3b3c105010665a3d002
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Git / 1.1 / 21e7329a632904350bb9a2e7f1b17b9967988db8
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin LDAP / 1.4 / 18ba3a13ba4c6c07e6b0ad77940a52734159c27e
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin C++ (Community) / 1.0-SNAPSHOT / 0
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Checkstyle / 2.3 / 7c62fe8a00123b8df1fa16cc25ad77888e50e811
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin PMD / 2.4.1 / 2f30e0a7177041a4fb9f7ecefdb301e2bfc15903
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Core / 5.1.2 / 2a52a7106b2bfbd659c591c2d6fc09ad0ab2db5c
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Java / 3.5 / 5c297217308e256603d5070aace960d3f5f2064b
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin C# / 4.2 / f0abfc62733669d3f28c8c41bb77298e776dccfd
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Cobertura / 1.6.3 / 1b2e281814f22ff8a5f89cc15701de2de522a167
2015.10.07 11:55:07 INFO  web[o.s.s.p.ServerPluginJarsInstaller] Deploy plugin Email notifications / 5.1.2 / 2a52a7106b2bfbd659c591c2d6fc09ad0ab2db5c
2015.10.07 11:55:08 INFO  web[o.s.s.p.RailsAppsDeployer] Deploy Ruby on Rails applications
```

**Comment by acopet** [comment]
**Issue reproduced when installing issue-assign plugin.**

This plugin does not support preview / incremental mode. Please have a look to following link for more details: http://stackoverflow.com/questions/31072421/why-does-the-sonarqube-analysis-fail-through-eclipse

**Comment by almorelle** [comment]
```-Dsonar.preview.excludePlugins=<plugin-id>``` definitely solved that issue.
Thank you.

I still can't get the SQ analysis in the PR but I'll create a different issue for that since it might not be linked.
