### ISSUE TITLE
I cannot make the plugin work. In debug mode, I don't get any additional information.

### ISSUE THREAD

**Issue by racodond** [AmadeusITGroup/sonar-stash#9]
Hi,

I cannot make the plugin work. In debug mode, I don't get any additional information. For example, even if I set a project that does not exist in Stash, I always get the same log:

```
ANALYSIS SUCCESSFUL
[DEBUG] [16:18:27.823] Post-jobs : org.sonar.plugins.stash.StashIssueReportingPostJob@14feab02
[INFO] [16:18:27.823] Executing post-job class org.sonar.plugins.stash.StashIssueReportingPostJob
```
How can I debug?

Thank you

Regards,

David RACODON

**Comment by acopet** [comment]
Hello David,
Could you please provide the command line used to launch your SQ analysis with all parameters?

**Comment by racodond** [comment]
Hi Antoine,

Here it is:

```
 mvn sonar:sonar -s maven-settings.xml -Dsonar.analysis.mode=incremental -Dstash.notification -Dstash.project=MISC -X -Dstash.repository=stash-web-post-receive-hooks-plugin -Dstash.pullrequest.id=11 -Dsonar.stash.password=xxx -Dsonar.host.url=https://sonar.nespresso.com
```

**Comment by acopet** [comment]
There was a mistake in README.md fixed through following PR #8: sonar prefix was missing on several options. Therefore, just add sonar prefix for following options:

  -Dstash.notification => -Dsonar.stash.notification
  -Dstash.project=MISC => -Dsonar.stash.project=MISC
  -Dstash.repository=stash-web-post-receive-hooks-plugin => -Dsonar.stash.repository=stash-web-post-receive-hooks-plugin
  -Dstash.pullrequest.id=11 => -Dsonar.stash.pullrequest.id=11

**Comment by acopet** [comment]
@racodond, did you manage to run the plugin with the proposed fix?

**Comment by racodond** [comment]
@acopet My apologies for my late reply. I'm one step ahead now running the command with the right parameters.

I'm now facing another issue but didn't have time to investigate yet. Let me copy the stack trace in case it might be related to the plugin or you might have any hint.

[DEBUG] [09:14:22.172] Trying to recover from failing to connect channel [id: 0xcef37ea1, /10.56.14.30:60825 => stash.nespresso.com/10.56.8.198:443] with a retry value of true 
[DEBUG] [09:14:22.181] Failed to recover from connect exception: javax.net.ssl.SSLHandshakeException: General SSLEngine problem with channel [id: 0xcef37ea1, /10.56.14.30:60825 => stash.nespresso.com/10.56.8.198:443]
[DEBUG] [09:14:22.189] General SSLEngine problem
java.net.ConnectException: General SSLEngine problem
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:131) [async-http-client-1.9.28.jar:na]
	at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37) [async-http-client-1.9.28.jar:na]
	at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:104) [async-http-client-1.9.28.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1460) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1314) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.3.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[na:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_45]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_45]
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218) [netty-3.10.3.Final.jar:na]
	... 18 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_45]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_45]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_45]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) ~[na:1.8.0_45]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[na:1.8.0_45]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_45]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[na:1.8.0_45]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[na:1.8.0_45]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[na:1.8.0_45]
	at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255) [netty-3.10.3.Final.jar:na]
	... 18 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[na:1.8.0_45]

**Comment by brice-pinguetti** [comment]
The plugin performs hostname verification during client authentication on Stash server.
As a consequence, the hostname in the Stash base URL field has to be complete in order to match the server SSL certificate's one.
So, when the hostname is defined by an alias in the plugin, the verification can't be validated.

In case you really want to use an alias to specify the hostname, the possibility to skip hostname verification is provided in this commit :    

brice-pinguetti/sonar-stash@eb99cd1298da694dbb0b9bcc6f7598e4373ab889

This feature adds a new field that configures the https client for accepting any certificate.

@racodond, please let me know if you manage to run the plugin with the proposed fix.

**Comment by acopet** [comment]
Hello David,

Did you manage to have a look to the solution proposed by Brice? Can we close this ticket?

Cheers,
Antoine

**Comment by racodond** [comment]
Hi Antoine,

I'm no longer working with the company where I was facing the issue so that I'm afraid that I cannot test the fix.

Regards,

David

**Comment by acopet** [comment]
Issue can be closed so!

Thanks,
Antoine

**Comment by Tetradeus** [comment]
Hello,

I am facing the same issue. I am reintegrating brice-pinguetti/sonar-stash@eb99cd1 to master branch. Would you be interested by a pr ?
